import connectDB from "@/lib/db";
import Post from "@/models/Post";
import Tag from "@/models/Tag";
import Category from "@/models/Category";
import User from "@/models/User";
import slugify from "slugify";

/**
 * Blog Service
 * Handles persisting and retrieving AI-generated blog data.
 */

/**
 * Checks if a blog post already exists for a given keyword.
 * Matches by title, focusKeyword, or if the slug contains the keyword.
 * 
 * @param {string} keyword 
 * @returns {Promise<Object|null>}
 */
export async function getBlogByKeyword(keyword) {
  await connectDB();
  const searchRegex = new RegExp(keyword.trim(), 'i');

  return await Post.findOne({
    $or: [
      { title: searchRegex },
      { "seo.focusKeyword": searchRegex },
      { slug: new RegExp(slugify(keyword, { lower: true, strict: true }), 'i') }
    ],
    status: 'published'
  }).populate('tags category author');
}

/**
 * Blog Save Service
 * Handles persisting AI-generated blog data to MongoDB.
 * 
 * @param {Object} blogData - Data from the Blog Agent workflow.
 * @returns {Promise<Object>} The saved post document.
 */
export async function saveBlog(blogData) {
  const { topic, content, slug: initialSlug, meta_description, tags } = blogData;

  await connectDB();

  // 1. Get or Create Tags
  const tagIds = await Promise.all(
    (tags || []).map(async (tagName) => {
      const tagSlug = slugify(tagName, { lower: true, strict: true });
      let tag = await Tag.findOne({ slug: tagSlug });
      if (!tag) {
        tag = await Tag.create({ name: tagName, slug: tagSlug });
      }
      return tag._id;
    })
  );

  // 2. Get Default Category (or create "AI Generated")
  let category = await Category.findOne({ slug: "ai-generated" });
  if (!category) {
    category = await Category.create({ 
      name: "AI Generated", 
      slug: "ai-generated",
      description: "Posts automatically generated by AI agents."
    });
  }

  // 3. Get Default Author (First admin or creator found)
  let author = await User.findOne({ role: "admin" });
  if (!author) {
      author = await User.findOne({}); // Fallback to any user
  }

  if (!author) {
      throw new Error("No author found in database to assign to the post.");
  }

  // 4. Ensure Unique Slug
  let finalSlug = initialSlug || slugify(topic, { lower: true, strict: true });
  let slugExists = await Post.findOne({ slug: finalSlug });
  let counter = 1;
  while (slugExists) {
    finalSlug = `${initialSlug}-${counter}`;
    slugExists = await Post.findOne({ slug: finalSlug });
    counter++;
  }

  // 5. Create the Post
  const newPost = await Post.create({
    title: topic,
    slug: finalSlug,
    excerpt: meta_description || "",
    content: content,
    author: author._id,
    category: category._id,
    tags: tagIds,
    status: "published", // Default to published for AI generated blogs
    publishedAt: new Date(),
    readingTime: Math.ceil(content.split(/\s+/).length / 200), // Basic calculation
    seo: {
      metaTitle: topic,
      metaDescription: meta_description,
      focusKeyword: topic,
    }
  });

  return newPost;
}
