import connectDB from "@/lib/db";
import Post from "@/models/Post";
import Tag from "@/models/Tag";
import Category from "@/models/Category";
import User from "@/models/User";
import UsedKeyword from "@/models/UsedKeyword";
import slugify from "slugify";

/**
 * Blog Service
 * Handles persisting and retrieving AI-generated blog data.
 */

/**
 * Checks if a blog post already exists for a given keyword.
 * Matches by title, focusKeyword, or if the slug contains the keyword.
 * 
 * @param {string} keyword 
 * @returns {Promise<Object|null>}
 */
export async function getBlogByKeyword(keyword) {
  await connectDB();
  const searchRegex = new RegExp(keyword.trim(), 'i');

  return await Post.findOne({
    $or: [
      { title: searchRegex },
      { "seo.focusKeyword": searchRegex },
      { slug: new RegExp(slugify(keyword, { lower: true, strict: true }), 'i') }
    ],
    status: 'published'
  }).populate('tags category author');
}

/**
 * Blog Save Service
 * Handles persisting AI-generated blog data to MongoDB.
 * 
 * @param {Object} blogData - Data from the Blog Agent workflow.
 * @returns {Promise<Object>} The saved post document.
 */
export async function saveBlog(blogData) {
  const { 
    topic, 
    content, 
    slug: initialSlug, 
    meta_description, 
    meta_title,
    focus_keyword,
    tags, 
    category: categoryName,
    excerpt,
    featured_image 
  } = blogData;

  await connectDB();

  // 1. Get or Create Tags
  const tagIds = await Promise.all(
    (tags || []).map(async (tagName) => {
      const cleanName = tagName.trim();
      const tagSlug = slugify(cleanName, { lower: true, strict: true });
      
      // Match by slug OR name (case-insensitive)
      let tag = await Tag.findOne({ 
        $or: [
          { slug: tagSlug },
          { name: new RegExp(`^${cleanName}$`, 'i') }
        ]
      });
      
      if (!tag) {
        tag = await Tag.create({ name: cleanName, slug: tagSlug });
      }
      return tag._id;
    })
  );

  // 2. Resolve Category
  let category = null;
  if (categoryName) {
    const cleanCat = categoryName.trim();
    category = await Category.findOne({ 
      $or: [
        { name: new RegExp(`^${cleanCat}$`, 'i') }, 
        { slug: slugify(cleanCat, { lower: true, strict: true }) }
      ] 
    });
  }
  
  if (!category) {
    category = await Category.findOne({ slug: "ai-generated" });
    if (!category) {
      category = await Category.create({ 
        name: "AI Generated", 
        slug: "ai-generated",
        description: "Posts automatically generated by AI agents."
      });
    }
  }

  // 3. Get Default Author
  let author = await User.findOne({ role: "admin" });
  if (!author) {
      author = await User.findOne({});
  }

  if (!author) {
      throw new Error("No author found in database to assign to the post.");
  }

  // 4. Ensure Unique Slug
  let finalSlug = initialSlug || slugify(topic, { lower: true, strict: true });
  let slugExists = await Post.findOne({ slug: finalSlug });
  let counter = 1;
  const originalSlug = finalSlug;
  while (slugExists) {
    finalSlug = `${originalSlug}-${counter}`;
    slugExists = await Post.findOne({ slug: finalSlug });
    counter++;
  }

  // 5. Create the Post
  const newPost = await Post.create({
    title: topic,
    slug: finalSlug,
    excerpt: excerpt || meta_description || "",
    content: content,
    featuredImage: featured_image || "",
    featuredImageAlt: topic,
    author: author._id,
    category: category._id,
    tags: tagIds,
    status: "published", 
    publishedAt: new Date(),
    readingTime: Math.ceil(content.split(/\s+/).length / 200),
    seo: {
      metaTitle: meta_title || topic,
      metaDescription: meta_description,
      focusKeyword: focus_keyword || topic,
    }
  });

  // Mark keyword as used
  await markKeywordUsed(focus_keyword || topic, 'success', newPost._id);

  return newPost;
}

/**
 * Checks if a keyword or slug is already in use.
 * Checks both the Post collection and the UsedKeyword collection.
 * 
 * @param {string} keyword 
 * @returns {Promise<boolean>}
 */
export async function isKeywordUsed(keyword) {
  await connectDB();
  const lowerKeyword = keyword.toLowerCase().trim();
  const slug = slugify(lowerKeyword, { lower: true, strict: true });

  // 1. Check UsedKeyword collection (fastest)
  const usedEntry = await UsedKeyword.findOne({ 
    $or: [{ keyword: lowerKeyword }, { slug: slug }] 
  });
  if (usedEntry) return true;

  // 2. Check Post collection (fallback for legacy/manually created posts)
  const existingPost = await Post.findOne({
    $or: [
      { "seo.focusKeyword": new RegExp(`^${lowerKeyword}$`, 'i') },
      { slug: slug }
    ]
  });
  
  return !!existingPost;
}

/**
 * Marks a keyword as used in the database.
 * 
 * @param {string} keyword 
 * @param {string} status - 'success' | 'failed'
 * @param {string} postId - (Optional) ID of the created post
 */
export async function markKeywordUsed(keyword, status = 'success', postId = null) {
  await connectDB();
  const lowerKeyword = keyword.toLowerCase().trim();
  const slug = slugify(lowerKeyword, { lower: true, strict: true });

  await UsedKeyword.findOneAndUpdate(
    { keyword: lowerKeyword },
    { 
      keyword: lowerKeyword,
      slug: slug,
      status: status,
      postId: postId,
      usedAt: new Date()
    },
    { upsert: true, new: true }
  );
}
